import os

Import('env')

env.SharedLibrary('libmpicommrank.so', ['mpi_comm_rank.cc'])

libpath = ['#lib', os.path.join(os.environ['HOME'], '.local', 'lib')]
libs = ['tango', 'gtest_main', 'gtest']
gtest_include = os.path.join(os.environ['HOME'], '.local', 'include')

test_env = env.Clone(CXXFLAGS=['-std=c++11', '-isystem {}'.format(gtest_include)],
                     LIBPATH=libpath,  LIBS=libs)
# The test code needs the internal headers.
test_env.Append(CPPPATH='#lib')

# Unit tests.
test_env.Program('coupling_manager_test.exe', ['coupling_manager_test.cc'])
test_env.Program('router_test.exe', ['router_test.cc'])
test_env.Program('tile_test.exe', ['tile_test.cc'])
test_env.Program('tango_test.exe', ['tango_test.cc'])
