import os

Import('env')

env.SharedLibrary('libmpicommbasic.so', ['mpi_comm_basic.cc'])

libpath = ['#lib', os.path.join(os.environ['HOME'], '.local', 'lib')]
libs = ['tango', 'gtest_main', 'gtest']
gtest_include = os.path.join(os.environ['HOME'], '.local', 'include')

test_env = env.Clone(CXXFLAGS=['-std=c++11', '-isystem {}'.format(gtest_include)],
                     LIBPATH=libpath,  LIBS=libs)
# The test code needs the internal headers.
test_env.Append(CPPPATH='#lib')

# Unit tests.
test_env.Program('tango_ftest.exe', ['tango_ftest.F90'])
test_env.Program('tango_ctest.exe', ['tango_ctest.cc'])
